### ISSUE TITLE
Add option to non-block cracked player

### ISSUE THREAD

**Issue by TyouZ54** [Corenb/PremiumConnector#15]
Please add a option to non-block cracked player in auth server.
Added "Block cracked player to switch server while they're not logged in with AuthMe. (You need to enable hook.bungeecord: true in your AuthMe config)"

For server don't using authme.

**Comment by Corenb** [comment]
I can do this but the player will be able to switch server without be registered by your third auth plugin via /server command if you allow all your players to use the command.

**Comment by TyouZ54** [comment]
> I can do this but the player will be able to switch server without be registered by your third auth plugin via /server command if you allow all your players to use the command.

Yes, because im using my own plugin for auth, i already block all command in the auth's server

**Comment by Corenb** [comment]
Please try the latest version
