### ISSUE TITLE
Something is happening with the plugin that does not log the user with the LockLogin when / premium is used

### ISSUE THREAD

**Issue by NosseidanMC** [Corenb/PremiumConnector#16]
12.01 19:02:39 [Server] INFO [PremiumConnector] Debug level set to INFO
12.01 19:02:39 [Server] SEVERE SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
12.01 19:02:39 [Server] SEVERE SLF4J: Defaulting to no-operation (NOP) logger implementation
12.01 19:02:39 [Server] SEVERE SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by Corenb** [comment]
Can you provide me wich Bungeecord fork's are you using and the version please ?
