### ISSUE TITLE
Unclear how to setup premium connector with LockLogin

### ISSUE THREAD

**Issue by Epicminemaster7** [Corenb/PremiumConnector#18]
I installed both versions of lock login bungee and premium connector I have looked through the configuration and I have looked through both of the configurations I have not found a way to link the authenticator plugin with the premium connector when i try to reset a player the command doesn't work and I am operator on all of my servers so this confuses me please help as soon as possible please and thanks -Epicminemaster

**Comment by Corenb** [comment]
Hello,

The hook between both plugin is automatically if LockLogin is present on your BungeeCord setup and you will see "LockLogin hook enabled." in console if the configuration is working.

For the reset command, server sends you a message ? No error on the console while executing the command ?
