### ISSUE TITLE
no command register in bungeecord

### ISSUE THREAD

**Issue by poohzaza166** [Corenb/PremiumConnector#23]
so i type /pemium|prem  and in bungeecord terminal and in game booth say command not found

**Comment by Corenb** [comment]
Hello, the plugin seems to be disable, can you check your Bungeecord logs and search for plugin error on startup or executing command ?

Just in case, command is premium* instead of pemium :)

**Comment by poohzaza166** [comment]
https://pastebin.pl/view/ca88a4a5 here is bunggecord log there is an error but the strangest part is i login to auth server and when i am done login it transfer me to lobby automaticlly i did enable debug mode

here is debug mode disable https://pastebin.pl/view/1353476b 


and yes i do have SQLite-for-BungeeCord.jar in my bungeecord plugin folder 

thanks for the support:)

**Comment by Corenb** [comment]
Error is here :
`08:54:33 [WARNING] Exception encountered when loading plugin: PremiumConnector
java.lang.IllegalArgumentException: Bad level "DEBUG"
    at java.logging/java.util.logging.Level.parse(Level.java:517)
    at eu.horyzon.premiumconnector.PremiumConnector.onEnable(PremiumConnector.java:60)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

«DEBUG» level don't exist, please refer you to https://docs.oracle.com/javase/7/docs/api/java/util/logging/Level.html

**Comment by Corenb** [comment]
Sorry I didn't see the second logs with :
`08:55:19 [SEVERE] java.sql.BatchUpdateException: batch entry 1: [SQLITE_ERROR] SQL error or missing database (near "MODIFY": syntax error)
08:55:19 [SEVERE]     at org.sqlite.jdbc3.JDBC3Statement.executeBatch(JDBC3Statement.java:210)
08:55:19 [SEVERE]     at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
08:55:19 [SEVERE]     at com.zaxxer.hikari.pool.HikariProxyStatement.executeBatch(HikariProxyStatement.java)
08:55:19 [SEVERE]     at eu.horyzon.premiumconnector.sql.DataSource.initDatabase(DataSource.java:65)
08:55:19 [SEVERE]     at eu.horyzon.premiumconnector.sql.DataSource.<init>(DataSource.java:47)
08:55:19 [SEVERE]     at eu.horyzon.premiumconnector.PremiumConnector.onEnable(PremiumConnector.java:76)
08:55:19 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
08:55:19 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
08:55:19 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
08:55:19 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)`

I guess certain MySQL statement don't works on SQL so I need to fix it. Please try to use the plugin with MySQL server meanwhile I fix it.

**Comment by poohzaza166** [comment]
thanks
