### ISSUE TITLE
[Idea/Add] SQLite Support 

### ISSUE THREAD

**Issue by Finoway** [Corenb/PremiumConnector#3]
Hello,

Would it be possible to use your plugin with SQLite? This would allow for some people to not absolutely need a database.

**Comment by Corenb** [comment]
Hi @Finoway ,

You can already use SQLite with the plugin. For that, you need to set the driver to `org.sqlite.JDBC` and install yourself the driver cause BungeeCord doesn't support SQLite per default :
Easy way : https://www.spigotmc.org/resources/sqlite-for-bungeecord.57191/
Hard way : https://gist.github.com/games647/d2a57abf90f707c0bd1107e432c580f3

**Comment by Finoway** [comment]
Hello I would like this to be more visible because personally I had not found. ^^

**Comment by Corenb** [comment]
I gonna add some help to the next release.

**Comment by Finoway** [comment]
Hello,

[the second link](https://gist.github.com/games647/d2a57abf90f707c0bd1107e432c580f3) you sent me can't work, the bitbucket link inside says 404. (https://bitbucket.org/xerial/sqlite-jdbc/downloads/)

**Comment by Finoway** [comment]
sorry to send a second message but could you do another way to download it because if I go through the first link and I click on download every other time I get a 405 error.

![image](https://user-images.githubusercontent.com/48923336/102008758-31057600-3d33-11eb-8d26-8fd22d4f92a7.png)

**Comment by Corenb** [comment]
Hmm it's weird cause the first link (spigot plugin) is working for me and I can download it without any issue.
For the second solution, you can directly download the driver on the official github repo : https://github.com/xerial/sqlite-jdbc
